default:
  server:
    dbhost: 192.168.1.38
    dbport: 5432
    dbname: "Rapid"
    dbuser: "postgres"
    dbpassword: "alpha##23SQL"
  zeitraum_name:
    - d30
    - d90
    - m12
    - y05
  zeitraum_api:
    - today 1-m
    - today 3-m
    - today 12-m
    - today+5-y
  suchbegriffe:
    LEH:
      - Aldi Süd
      - Aldi Nord
      - Lidl
      - Netto
      - Norma
    Baumarkt:
      - obi
      - bauhaus
      - hagebaumarkt
    Touristik_1:
      - kreuzfahrt
      - flussreise
